#-- Creation: 22 Sep 2024 
#-- Version: 2.5 ALPHA

blueprint:
  name: Hue Dimmer v2 (v2.5 ALPHA)
  description: >
    Control a light entity/group with a Philips Hue Dimmer Switch (v2).
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch
      description: Pick a RWL022 Dimmer Switch
      selector:
        device:
          integration: zha
          entity:
            domain: sensor
            device_class: battery
    initial_color_temp:
      name: Default Colour Temperature
      description: The default color temperature in Kelvin when the lights are turned on.
      selector:
        color_temp:
          min: 2100
          max: 6500
          unit: kelvin
      default: 4500
    light_entities:
      name: The light entities to control.
      description: The light entities to be controlled by the dimmer switch.
      selector:
        target:
          entity:
            domain: light
    brightness_steps:
      name: Percentage to increase or decrease brightness.
      description: The percentage to increase or decrease brightness when the button is pressed.
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
      default: 18

  mode: single

  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: !input remote
        cluster_id: 64512

  action:
    - variables:
        command: "{{ trigger.event.data.command }}"
        light_entity: !input light_entity
        brightness_steps: !input brightness_steps
        initial_color_temp: !input initial_color_temp
        
    - choose:
        # Handle on_press (single press)
        - conditions: "{{ command == 'on_press' }}"
          sequence:
            - service: light.toggle
              data:
                target: !input light_entity
                transition: 0.4
                brightness: 255
                color_temp_kelvin: !input initial_color_temp
