blueprint:
  name: Philips Hue Dimmer Switch v2 Custom
  description: "Control lights with a Philips Hue Dimmer Switch v2. Supports custom actions for button clicks, including single and double press."
  domain: automation
  input:
    dimmer_switch:
      name: Hue Dimmer Switch
      description: The Philips Hue v2 Smart Dimmer Switch device that will send the commands
      selector:
        device:
          integration: zha
          model: RWL022
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: light
    top_double_press:
      name: Top Button Double Press Action
      description: Action to take on a double press of the top button
      default: []
      selector:
        action: {}
    off_double_press:
      name: Off Button Double Press Action
      description: Action to take on a double press of the off button
      default: []
      selector:
        action: {}
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input dimmer_switch
action:
  - variables:
      button: "{{ trigger.event.data.args.button }}"
      command_type: "{{ trigger.event.data.command }}"
      light_group: "{{ input.light.id }}"

  - choose:
      ######################################################################
      ## Button Logic
      ######################################################################
      - conditions:
          - condition: template
            value_template: "{{ button == 'top' }}"
        sequence:
          - choose:
              # Top Single Press
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'press' }}"
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ light_group }}"
                      brightness: 255
                      color_temp: 5000
                      transition: 1
              # Top Double Press
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'double_press' }}"
                sequence:
                  - choose:
                      - conditions: "{{ input.top_double_press != [] }}"
                        sequence: !input "top_double_press"

      - conditions:
          - condition: template
            value_template: "{{ button == 'off' }}"
        sequence:
          - choose:
              # Off Single Press
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'press' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: "{{ light_group }}"
              # Off Double Press
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'double_press' }}"
                sequence:
                  - choose:
                      - conditions: "{{ input.off_double_press != [] }}"
                        sequence: !input "off_double_press"

      - conditions:
          - condition: template
            value_template: "{{ button == 'up' }}"
        sequence:
          # Up Button Single Press
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'press' }}"
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ light_group }}"
                      brightness_step: 50
                      transition: 1

      - conditions:
          - condition: template
            value_template: "{{ button == 'down' }}"
        sequence:
          # Down Button Single Press
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'press' }}"
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ light_group }}"
                      brightness_step: -50
                      transition: 1
