#-- Creation: 22 Sep 2024
#-- Version: 1.7.2

blueprint:
  name: Philips Hue Dimmer RWL022 (v1.7.2)
  description: >
    Control multiple light entities with a Philips Hue Dimmer Switch
    (v2), with optional custom actions for on and double press off.
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch v2
      description: The Philips Hue v2 Smart Dimmer Switch device.
      selector:
        device:
          integration: zha
          model: RWL022
    light_entities:
      name: The light entities to control.
      description: The light entities to be controlled by the dimmer switch.
      selector:
        target:
          entity:
            domain: light
    brightness_steps:
      name: Percentage to increase or decrease brightness.
      description: The percentage to increase or decrease brightness when the button is pressed.
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
      default: 18
    color_temp:
      name: Default Colour Temperature
      description: The default color temperature in Kelvin when the lights are turned on.
      selector:
        color_temp:
          min: 2100
          max: 6500
          unit: kelvin
    custom_on_actions:
      name: Custom Actions for Light On
      description: Custom actions to override the default on action.
      default: []
      selector:
        action: {}
    custom_off_double_actions:
      name: Custom Actions for Light Off Double Press
      description: Custom actions to override the default off double press action.
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

variables:
  light_entities: !input "light_entities"
  brightness_steps: !input "brightness_steps"
  color_temp: !input "color_temp"
  custom_on_actions: !input "custom_on_actions"
  custom_off_double_actions: !input "custom_off_double_actions"

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "remote"
      cluster_id: 64512

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ command == 'on_press' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ custom_on_actions | length > 0 }}"
                sequence:
                  - service: "{{ custom_on_actions[0].service }}"
                    data: "{{ custom_on_actions[0].data }}"
              - default:
                  - service: light.turn_on
                    target: !input "light_entities"
                    data:
                      transition: 0.4
                      brightness: 255
                      color_temp_kelvin: "{{ color_temp }}"

      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ command == 'up_press' }}"
              - condition: template
                value_template: "{{ command == 'up_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input "light_entities"
            data:
              transition: 0.5
              brightness_step_pct: "{{ brightness_steps }}"

      - conditions:
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ command == 'down_press' }}"
              - condition: template
                value_template: "{{ command == 'down_hold' }}"
        sequence:
          - service: light.turn_on
            target: !input "light_entities"
            data:
              transition: 0.5
              brightness_step_pct: "{{ brightness_steps * -1 }}"

      - conditions:
          - condition: template
            value_template: "{{ command == 'off_press' }}"
        sequence:
          - service: light.turn_off
            target: !input "light_entities"
            data:
              transition: 0.4

      - conditions:
          - condition: template
            value_template: "{{ command == 'off_double_press' }}"
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ custom_off_double_actions | length > 0 }}"
                sequence:
                  - service: "{{ custom_off_double_actions[0].service }}"
                    data: "{{ custom_off_double_actions[0].data }}"
              - default:
                  - service: light.turn_off
                    target: !input "light_entities"
                    data:
                      transition: 0.4
