#-- Creation: 22 Sep 2024 
#-- Version: 2.27 ALPHA
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
blueprint:
  name: Hue Dimmer v2 (v2.27 ALPHA)
  description: >
    Control a light entity/group with a Philips Hue Dimmer Switch (v2).
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch
      description: Pick a RWL022 Dimmer Switch
      selector:
        device:
          integration: zha
          entity:
            domain: sensor
            device_class: battery
    initial_color_temp:
      name: Default Colour Temperature
      description: The default color temperature in Kelvin when the lights are turned on.
      selector:
        color_temp:
          min: 2100
          max: 6500
          unit: kelvin
      default: 3000
    light_entities:
      name: The light entities to control.
      description: The light entities to be controlled by the dimmer switch.
      selector:
        target:
          entity:
            domain: light
    brightness_steps:
      name: Percentage to increase or decrease brightness.
      description: The percentage to increase or decrease brightness when the button is pressed.
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
      default: 18

mode: single

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input remote
      cluster_id: 64512

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      brightness_steps: !input brightness_steps
      light_entities: !input light_entities
      light_entities_expanded: "{{ expand(light_entities) | selectattr('domain', 'equalto', 'light') | list }}"
      first_light: "{{ light_entities_expanded | first if light_entities_expanded | length > 0 else none }}"
      current_color_temp: "{{ state_attr(first_light, 'color_temp_kelvin') | int(default=0) if first_light else 0 }}"

  # Log variables and initial conditions
  - service: system_log.write
    data:
      level: info
      message: >
        [DEBUG] Command received: {{ command }}
        [
