blueprint:
  name: Hue Dimmer MegaButton
  description: >
    Control a light with a Philips Hue Dimmer v2 (ZHA integration).

    - Single press on the top button will turn the light on with predefined brightness and color temperature.
    - Double press on the top button will trigger a custom action.
    - The bottom button will turn off all the lights.
  
  domain: automation
  input:
    dimmer_switch:
      name: Hue Dimmer Switch
      description: The Philips Hue v2 Smart Dimmer Switch device that will send the commands
      selector:
        device:
          integration: zha
          model: RWL022
    light_group:
      name: Light(s)
      description: Select the light(s) to control
      selector:
        target:
          entity:
            domain: light
    top_double_press:
      name: Top Double Press Action
      description: Action to run when the top button is double-pressed
      default: []
      selector:
        action: {}
    brightness:
      name: Brightness Percentage
      description: Brightness of the light(s) when turning on
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider
    kelvin:
      name: Color Temperature (Kelvin)
      description: Color temperature of the light(s) when turning on
      default: 4500
      selector:
        number:
          min: 2000
          max: 6500
          unit_of_measurement: "K"
          mode: slider

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "dimmer_switch"

action:
  - variables:
      button: "{{ trigger.event.data.args.button }}"
      command_type: "{{ trigger.event.data.command }}"
      light_group: !input "light_group"

  - choose:
      ######################################################################
      ## Top Button Logic
      ######################################################################
      - conditions:
          - condition: template
            value_template: "{{ button == 'top' }}"
        sequence:
          - choose:
              # Top Single Press
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'press' }}"
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ light_group }}"
                      brightness_pct: !input "brightness"
                      kelvin: !input "kelvin"
                      transition: 1

              # Top Double Press
              - conditions:
                  - condition: template
                    value_template: "{{ command_type == 'double_press' }}"
                sequence:
                  - choose:
                      - conditions: "{{ input.top_double_press != [] }}"
                        sequence: !input "top_double_press"

      ######################################################################
      ## Bottom Button Logic
      ######################################################################
      - conditions:
          - condition: template
            value_template: "{{ button == 'bottom' }}"
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ light_group }}"
            data:
              transition: 1

mode: single
