blueprint:
  name: Philips Hue Dimmer RWL022
  description: >
    Control a single light entity with a Philips Hue Dimmer Switch (v2).

    Blueprint Version: 2
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch
      description: Pick a RWL022 Dimmer Switch
      selector:
        device:
          integration: zha
          entity:
            domain: sensor
            device_class: battery
    light_entity:
      name: The light entity to control.
      description: The light entity to be controlled by the dimmer switch.
      selector:
        entity:
          domain: light
    brightness_steps:
      name: Percentage to increase or decrease brightness.
      description: The percentage to increase or decrease brightness when the button is pressed.
      selector:
        number:
          min: 1
          max: 25
          unit_of_measurement: "%"
  source_url: https://gist.github.com/brodock/0c85f4882b885d4d5499cd88d155c38c
mode: restart
max_exceeded: silent
variables:
  light_entity: !input "light_entity"
  brightness_steps: !input "brightness_steps"
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "remote"
      cluster_id: 64512
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      light_on: "{{ is_state(light_entity, 'on') }}"
  - choose:
      - conditions: "{{ command == 'on_short_release' }}"
        sequence:
          service: light.toggle
          data:
            entity_id: !input "light_entity"
            transition: 0.5
      - conditions: "{{ command == 'off_short_release' }}"
        sequence:
          service: light.toggle
          data:
            entity_id: !input "light_entity"
            transition: 0.5
      - conditions:
          - condition: or
            conditions:
              - "{{ command == 'up_short_release' }}"
              - "{{ command == 'up_hold' }}"
        sequence:
          service: light.turn_on
          data:
            entity_id: !input "light_entity"
            transition: 0.5
            brightness_step_pct: "{{ brightness_steps }}"
      - conditions:
          - condition: or
            conditions:
              - "{{ command == 'down_short_release' }}"
              - "{{ command == 'down_hold' }}"
        sequence:
          service: light.turn_on
          data:
            entity_id: !input "light_entity"
            transition: 0.5
            brightness_step_pct: "{{ brightness_steps*-1 }}"
