#INDEV
blueprint:
  name: Philips Hue Dimmer v2 - Light Control
  description: >
    Control a light with a Philips Hue Dimmer v2 (ZHA integration).

    - Short press on the "off" button will turn the light off.

  domain: automation
  input:
    dimmer_switch:
      name: Hue Dimmer Switch
      description: The Philips Hue v2 Smart Dimmer Switch device that will send the commands
      selector:
        device:
          integration: zha
          model: RWL022
    light_target:
      name: Light(s)
      description: Select the light(s) to control
      selector:
        target:
          entity:
            domain: light

trigger:
  - platform: device
    device_id: !input "dimmer_switch"
    domain: zha

action:
  - service: light.turn_off
    target: !input "light_target"

mode: single
