# Blueprint version 1.24
blueprint:
  domain: automation
  name: Hue v2 Dimmer for Lights
  description: "Philips Hue v2 Smart Dimmer Switch using Zigbee Home Automation"
  input:
    zha_device:
      name: ZHA Device
      description: The Philips Hue v2 Smart Dimmer Switch device that will send the commands
      selector:
        device:
          integration: zha
          model: RWL022

    light_group:
      name: Light (Group)
      description: The light or light group to control
      selector:
        target:
          entity:
            domain: light

  trigger:
    - platform: event
      event_type: zha_event

  condition:
    - condition: template
      value_template: "{{ trigger.event.data.device_id == zha_device.id }}"

  action:
    - variables:
        button: "{{ trigger.event.data.args.button }}"
        command_type: "{{ trigger.event.data.command }}"

    - choose:
        # Top Button (Power on/off Button)
        - conditions:
            - condition: template
              value_template: "{{ button == 'top' }}"
          sequence:
            - choose:
                # Single Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'press' }}"
                  sequence:
                    - service: light.turn_on
                      data:
                        target: "{{ light_group }}"
                        brightness: 255
                        color_temp: 5000
                        transition: 1
                        
                # Double Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'double_press' }}"
                  sequence: []
                        
                # Triple Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'triple_press' }}"
                  sequence: []
                        
                # Hold
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'hold' }}"
                  sequence: []

        # Brightness Up Button
        - conditions:
            - condition: template
              value_template: "{{ button == 'up' }}"
          sequence:
            - choose:
                # Single Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'press' }}"
                  sequence:
                    - service: light.turn_on
                      data:
                        target: "{{ light_group }}"
                        brightness_step: 10

                # Double Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'double_press' }}"
                  sequence:
                    - service: light.turn_on
                      data:
                        target: "{{ light_group }}"
                        brightness: 255

                # Triple Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'triple_press' }}"
                  sequence: []

                # Hold
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'hold' }}"
                  sequence:
                    - repeat:
                        while:
                          - condition: state
                            entity_id: "{{ light_group }}"
                            state: "on"
                        sequence:
                          - service: light.turn_on
                            data:
                              target: "{{ light_group }}"
                              brightness_step: 30

        # Brightness Down Button
        - conditions:
            - condition: template
              value_template: "{{ button == 'down' }}"
          sequence:
            - choose:
                # Single Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'press' }}"
                  sequence:
                    - service: light.turn_on
                      data:
                        target: "{{ light_group }}"
                        brightness: >
                          {% set current_brightness = state_attr(light_group, 'brightness') | default(255) %}
                          {% set new_brightness = current_brightness - 20 %}
                          {% if new_brightness < 3 %}
                            3
                          {% else %}
                            {{ new_brightness }}
                          {% endif %}

                # Double Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'double_press' }}"
                  sequence:
                    - service: light.turn_on
                      data:
                        target: "{{ light_group }}"
                        brightness: 3

                # Triple Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'triple_press' }}"
                  sequence: []

                # Hold
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'hold' }}"
                  sequence:
                    - repeat:
                        while:
                          - condition: state
                            entity_id: "{{ light_group }}"
                            state: "on"
                        sequence:
                          - service: light.turn_on
                            data:
                              target: "{{ light_group }}"
                              brightness: >
                                {% set current_brightness = state_attr(light_group, 'brightness') | default(255) %}
                                {% set new_brightness = current_brightness - 30 %}
                                {% if new_brightness < 3 %}
                                  3
                                {% else %}
                                  {{ new_brightness }}
                                {% endif %}

        # Bottom Button (Power Off Button)
        - conditions:
            - condition: template
              value_template: "{{ button == 'bottom' }}"
          sequence:
            - choose:
                # Single Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'press' }}"
                  sequence:
                    - service: light.turn_on
                      data:
                        target: "{{ light_group }}"
                        brightness: 1
                        color_temp: 5000
                        transition: 1
                    - service: light.turn_off
                      data:
                        target: "{{ light_group }}"

                # Double Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'double_press' }}"
                  sequence: []

                # Triple Press
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'triple_press' }}"
                  sequence: []

                # Hold
                - conditions:
                    - condition: template
                      value_template: "{{ command_type == 'hold' }}"
                  sequence: []
