blueprint:
  domain: automation
  name: Philips Hue v2 Smart Dimmer Switch
  description: "Philips Hue v2 Smart Dimmer Switch using Zigbee Home Automation"
  input:
    zha_device:
      name: ZHA Device
      description: List of available Philips Hue v2 Smart Dimmer Switch devices
      selector:
        device:
          integration: zha
          model: RWL022
          multiple: true
    top_press_override:
      name: Top Press Override
      description: Script to override the default top press action (default - turn on light at full brightness and 5000K color temperature)
      default: []
      selector:
        action: null
  mode: single
  max_exceeded: silent
  variables:
    device_id: !input "zha_device"
    top_press_override: !input "top_press_override"
  trigger:
    - platform: event
      event_type: zha_event
  condition: "{{ trigger.event.data.device_id == device_id }}"
  action:
    - variables:
        button: "{{ trigger.event.data.args.button }}"
        command_type: "{{ trigger.event.data.command }}"
    - service: logbook.log
      data:
        name: Button
        message: "{{ button }}"
    - service: logbook.log
      data:
        name: Command
        message: "{{ command_type }}"
    - choose:
        # Top Button (Power on/off Button)
        - conditions:
            - condition: template
              value_template: "{{ button == 'top' }}"
          sequence:
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ top_press_override }}"
                  sequence: !input "top_press_override"
                default:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ device_id }}"
                      brightness: 255
                      color_temp: 5000
                      transition: 1
        # Brightness Up Button
        - conditions:
            - condition: template
              value_template: "{{ button == 'up' }}"
          sequence:
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ brightness_up_override }}"
                  sequence: !input "brightness_up_override"
                default:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ device_id }}"
                      brightness_step: 10
        # Brightness Down Button
        - conditions:
            - condition: template
              value_template: "{{ button == 'down' }}"
          sequence:
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ brightness_down_override }}"
                  sequence: !input "brightness_down_override"
                default:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ device_id }}"
                      brightness_step: -10
                      brightness: "{{ state_attr(device_id, 'brightness')|default(255) | max(1) }}"
        # Bottom Button (Power Off Button)
        - conditions:
            - condition: template
              value_template: "{{ button == 'bottom' }}"
          sequence:
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ bottom_press_override }}"
                  sequence: !input "bottom_press_override"
                default:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ device_id }}"
                      brightness: 1
                      color_temp: 5000
                      transition: 1
                  - service: light.turn_off
                    data:
                      entity_id: "{{ device_id }}"
    - choose:
        # Up Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'up_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: "{{ device_id }}"
                brightness: 255
        # Down Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'down_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: "{{ device_id }}"
                brightness: 1
        # Top Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'top_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: "{{ device_id }}"
                brightness: 255
        # Bottom Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'bottom_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                entity_id: "{{ device_id }}"
                brightness: 1
    - choose:
        # Up Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'up_hold' }}"
          sequence:
            - repeat:
                while:
                  - condition: state
                    entity_id: "{{ device_id }}"
                    state: "on"
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ device_id }}"
                      brightness_step: 20
        # Down Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'down_hold' }}"
          sequence:
            - repeat:
                while:
                  - condition: state
                    entity_id: "{{ device_id }}"
                    state: "on"
                sequence:
                  - service: light.turn_on
                    data:
                      entity_id: "{{ device_id }}"
                      brightness_step: -20
        # Top Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'top_hold' }}"
          sequence: []
        # Bottom Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'bottom_hold' }}"
          sequence: []
