# Blueprint version 1.24
blueprint:
  name: Hue v2 Dimmer for Lights
  description: "Philips Hue v2 Smart Dimmer Switch using Zigbee Home Automation"
  domain: automation
  input:
    zha_device:
      name: ZHA Device
      description: The Philips Hue v2 Smart Dimmer Switch device that will send the commands
      selector:
        device:
          integration: zha
          model: RWL022

    light_group:
      name: Light
      description: The light(s) to control
      selector:
        target:
          entity:
            domain: light

  trigger:
    - platform: event
      event_type: zha_event

  condition:
    - condition: template
      value_template: "{{ trigger.event.data.device_id == zha_device.id }}"
