# Blueprint version 1.15
blueprint:
  domain: automation
  name: Philips Hue v2 Smart Dimmer Switch
  description: "Philips Hue v2 Smart Dimmer Switch using Zigbee Home Automation"
  input:
    zha_device:
      name: ZHA Device
      description: List of available Philips Hue v2 Smart Dimmer Switch devices
      selector:
        device:
          integration: zha
          model: RWL022
    light_group:
      name: Light or Light Group
      description: The light or light group to control
      selector:
        target:
          entity:
            domain: light
    top_press_override:
      name: Top Press Override
      description: Script to override the default top press action (default - turn on light at full brightness and 5000K color temperature)
      default: []
      selector:
        action: null
  mode: single
  max_exceeded: silent
  variables:
    device_id: !input "zha_device"
    light_group: !input "light_group"
    top_press_override: !input "top_press_override"
  trigger:
    - platform: event
      event_type: zha_event
  condition: "{{ trigger.event.data.device_id == device_id }}"
  action:
    - variables:
        button: "{{ trigger.event.data.args.button }}"
        command_type: "{{ trigger.event.data.command }}"
    - choose:
        # Top Button (Power on/off Button)
        - conditions:
            - condition: template
              value_template: "{{ button == 'top' }}"
          sequence:
            - choose:
                - conditions:
                    - condition: template
                      value_template: "{{ top_press_override }}"
                  sequence: !input "top_press_override"
                default:
                  - service: light.turn_on
                    data:
                      target: "{{ light_group }}"
                      brightness: 255
                      color_temp: 5000
                      transition: 1
        # Brightness Up Button
        - conditions:
            - condition: template
              value_template: "{{ button == 'up' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness_step: 10
        # Brightness Down Button
        - conditions:
            - condition: template
              value_template: "{{ button == 'down' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness_step: -10
        # Bottom Button (Power Off Button)
        - conditions:
            - condition: template
              value_template: "{{ button == 'bottom' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 1
                color_temp: 5000
                transition: 1
            - service: light.turn_off
              data:
                target: "{{ light_group }}"
    - choose:
        # Up Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'up_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 255
        # Up Button Triple Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'up_triple_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 1
        # Down Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'down_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 1
        # Down Button Triple Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'down_triple_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 255
        # Top Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'top_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 255
        # Top Button Triple Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'top_triple_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 1
        # Bottom Button Double Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'bottom_double_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 1
        # Bottom Button Triple Press
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'bottom_triple_press' }}"
          sequence:
            - service: light.turn_on
              data:
                target: "{{ light_group }}"
                brightness: 255
    - choose:
        # Up Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'up_hold' }}"
          sequence:
            - repeat:
                while:
                  - condition: state
                    entity_id: "{{ light_group }}"
                    state: "on"
                sequence:
                  - service: light.turn_on
                    data:
                      target: "{{ light_group }}"
                      brightness_step: 20
        # Down Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'down_hold' }}"
          sequence:
            - repeat:
                while:
                  - condition: state
                    entity_id: "{{ light_group }}"
                    state: "on"
                sequence:
                  - service: light.turn_on
                    data:
                      target: "{{ light_group }}"
                      brightness_step: -20
        # Top Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'top_hold' }}"
          sequence: []
        # Bottom Button Hold
        - conditions:
            - condition: template
              value_template: "{{ command_type == 'bottom_hold' }}"
          sequence: []
