blueprint:
  name: "TuYa Smart Knob (TS004F) v1.8"
  description: "Control devices and scenes with single tap, double tap, and rotation actions from a TuYa Smart Knob (TS004F)."
  domain: automation
  input:
    knob_device:
      name: "Smart Knob"
      description: "Select your TuYa Smart Knob (TS004F) device."
      selector:
        device:
          integration: zha
    single_tap_action:
      name: "Single Tap Action"
      description: "Action to perform on a single tap."
      default: []
      selector:
        action: {}
    double_tap_action:
      name: "Double Tap Action"
      description: "Action to perform on a double tap."
      default: []
      selector:
        action: {}
    rotate_left_action:
      name: "Rotate Left Action"
      description: "Action to perform on rotation to the left (CCW)."
      default: []
      selector:
        action: {}
    rotate_right_action:
      name: "Rotate Right Action"
      description: "Action to perform on rotation to the right (CW)."
      default: []
      selector:
        action: {}
    double_tap_timeout:
      name: "Double Tap Timeout (seconds)"
      description: "Maximum time between taps for a double tap to be registered."
      default: 0.4
      selector:
        number:
          min: 0.1
          max: 1.0
          step: 0.1

variables:
  double_tap_counter: 0

mode: restart
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input knob_device

action:
  - choose:
      - conditions:
          - "{{ trigger.event.data.command == 'toggle' }}"
        sequence:
          - service: variable.set_variable
            data:
              variable: double_tap_counter
              value: "{{ double_tap_counter + 1 }}"
          - delay:
              seconds: !input double_tap_timeout
          - choose:
              - conditions:
                  - "{{ double_tap_counter == 2 }}"
                sequence: !input double_tap_action
              default: !input single_tap_action
          - service: variable.set_variable
            data:
              variable: double_tap_counter
              value: 0
      - conditions:
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 1 }}"
        sequence: !input rotate_left_action
      - conditions:
          - "{{ trigger.event.data.command == 'step' }}"
          - "{{ trigger.event.data.params.step_mode == 0 }}"
        sequence: !input rotate_right_action
    default: []
