blueprint:
  name: "TuYa Smart Knob (TS004F) v1.10"
  description: "Control devices and scenes with tap and rotation actions from a TuYa Smart Knob (TS004F)."
  domain: automation
  input:
    knob_device:
      name: "Smart Knob"
      description: "Select your TuYa Smart Knob (TS004F) device."
      selector:
        device:
          integration: zha # Or deconz, zigbee2mqtt
    toggle_action:
      name: "Tap"
      description: "Action to perform on a tap on the top."
      default: []
      selector:
        action: {}
    rotate_left_action:
      name: "Rotate Left"
      description: "Action to perform on rotation to the left (CCW)."
      default: []
      selector:
        action: {}
    rotate_right_action:
      name: "Rotate Right Action"
      description: "Action to perform on rotation to the right (CW)."
      default: []
      selector:
        action: {}

mode: restart
trigger:
  - platform: event
    event_type: zha_event # Or deconz_event, mqtt for Zigbee2MQTT
    event_data:
      device_id: !input knob_device

action:
  - choose:
      - conditions:
          - "{{ trigger.event.data.command == 'toggle' }}"
        sequence: !input toggle_action
      - conditions:
          - "{{ trigger.event.data.command == 'step' }}" # Condition for rotation
          - "{{ trigger.event.data.params.step_mode == 1 }}" # Check for rotation direction (Down/CCW)
        sequence: !input rotate_left_action
      - conditions:
          - "{{ trigger.event.data.command == 'step' }}" # Condition for rotation
          - "{{ trigger.event.data.params.step_mode == 0 }}" # Check for rotation direction (Up/CW)
        sequence: !input rotate_right_action
    default: []
