blueprint:
  name: "TuYa Smart Knob (TS004F) v1.1" # Version added, "Actions" removed, incremented to v1.1
  description: "Control devices and scenes with click and rotation actions from a TuYa Smart Knob (TS004F)."
  domain: automation
  input:
    knob_device:
      name: "Smart Knob"
      description: "Select your TuYa Smart Knob (TS004F) device."
      selector:
        device:
          integration: zha # Or deconz, zigbee2mqtt
    single_press_action:
      name: "Single Press Action"
      description: "Action to perform on a single press."
      default: []
      selector:
        action: {}
    double_press_action:
      name: "Double Press Action"
      description: "Action to perform on a double press."
      default: []
      selector:
        action: {}
    long_press_action:
      name: "Long Press Action"
      description: "Action to perform on a long press."
      default: []
      selector:
        action: {}
    rotation_left_action:
      name: "Rotation Left Action"
      description: "Action to perform on rotation to the left."
      default: []
      selector:
        action: {}
    rotation_right_action:
      name: "Rotation Right Action"
      description: "Action to perform on rotation to the right."
      default: []
      selector:
        action: {}

mode: restart
trigger:
  - platform: event
    event_type: zha_event # Or deconz_event, mqtt for Zigbee2MQTT
    event_data:
      device_id: !input knob_device

action:
  - choose:
      - conditions:
          - "{{ trigger.event.data.command == 'single' }}"
        sequence: !input single_press_action
      - conditions:
          - "{{ trigger.event.data.command == 'double' }}"
        sequence: !input double_press_action
      - conditions:
          - "{{ trigger.event.data.command == 'hold' }}" # Or 'long_press'
        sequence: !input long_press_action
      - conditions:
          - "{{ trigger.event.data.args.rotation == 'CCW' }}" # Check your events
        sequence: !input rotation_left_action
      - conditions:
          - "{{ trigger.event.data.args.rotation == 'CW' }}" # Check your events
        sequence: !input rotation_right_action
    default: []
