# The cycling of scenes doesn't work

blueprint:
  name: Philips Hue Dimmer ZHA (Optional Scene Cycling)
  description: >
    Control lights with the Philips Hue Dimmer Switch (RWL022) using ZHA.
    The top button cycles through scenes if defined. Includes brightness control and toggle.
  domain: automation
  input:
    remote:
      name: Philips Hue Dimmer Switch v2
      description: The Philips Hue v2 Smart Dimmer Switch device.
      selector:
        device:
          integration: zha
          model: RWL022
    light_entities:
      name: The light entities to control.
      description: The light entities to be controlled by the dimmer switch.
      selector:
        target:
          entity:
            domain: light
    brightness_steps:
      name: Percentage to increase or decrease brightness.
      description: The percentage to increase or decrease brightness when the button is pressed.
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
      default: 18
    color_temp:
      name: Default Colour Temperature
      description: The default color temperature in Kelvin when the lights are turned on.
      selector:
        color_temp:
          min: 2100
          max: 6500
          unit: kelvin
      default: 4500
    scene_1:
      name: Scene 1 (Optional)
      description: The first scene to activate (optional).
      selector:
        entity:
          domain: scene
          multiple: false
    scene_2:
      name: Scene 2 (Optional)
      description: The second scene to activate (optional).
      selector:
        entity:
          domain: scene
          multiple: false
      default: null
    scene_3:
      name: Scene 3 (Optional)
      description: The third scene to activate (optional).
      selector:
        entity:
          domain: scene
          multiple: false
      default: null
    scene_4:
      name: Scene 4 (Optional)
      description: The fourth scene to activate (optional).
      selector:
        entity:
          domain: scene
          multiple: false
      default: null

mode: single
max_exceeded: silent

variables:
  current_scene: "{{ states('input_number.scene_counter') | int(0) }}"

  light_entities: !input "light_entities"
  brightness_steps: !input "brightness_steps"
  color_temp: !input "color_temp"
#  scene_1: !input "scene_1"
#  scene_2: !input "scene_2"
#  scene_3: !input "scene_3"
#  scene_4: !input "scene_4"

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input "remote"
      cluster_id: 64512

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'on_short_release' }}"
        sequence:
          - choose:
              # Cycle through only scenes that are defined.
              - conditions:
                  - condition: template
                    value_template: "{{ current_scene == 0 and scene_1 is defined and scene_1 != none }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_1
                  - service: input_number.set_value
                    data:
                      entity_id: input_number.scene_counter
                      value: 1
              - conditions:
                  - condition: template
                    value_template: "{{ current_scene == 1 and scene_2 is defined and scene_2 != none }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_2
                  - service: input_number.set_value
                    data:
                      entity_id: input_number.scene_counter
                      value: 2
              - conditions:
                  - condition: template
                    value_template: "{{ current_scene == 2 and scene_3 is defined and scene_3 != none }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_3
                  - service: input_number.set_value
                    data:
                      entity_id: input_number.scene_counter
                      value: 3
              - conditions:
                  - condition: template
                    value_template: "{{ current_scene == 3 and scene_4 is defined and scene_4 != none }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_4
                  - service: input_number.set_value
                    data:
                      entity_id: input_number.scene_counter
                      value: 0
              # Fallback to reset to Scene 1 if no scenes are defined
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (scene_1 == none or scene_1 == '') and 
                         (scene_2 == none or scene_2 == '') and 
                         (scene_3 == none or scene_3 == '') and 
                         (scene_4 == none or scene_4 == '') }}
                sequence:
                  - service: input_number.set_value
                    data:
                      entity_id: input_number.scene_counter
                      value: 0
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'up_short_release' }}"
        sequence:
          - service: light.turn_on
            target: !input light_entities
            data:
              brightness_step_pct: "{{ brightness_steps }}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'down_short_release' }}"
        sequence:
          - service: light.turn_on
            target: !input light_entities
            data:
              brightness_step_pct: "-{{ brightness_steps }}"
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'off_short_release' }}"
        sequence:
          - service: light.turn_off
            target: !input light_entities
